add 'DROP TABLE IF EXISTS' requests in the beginning of clevertricks.sql
WildCodeSchool/tours-php-2103-project2-clevertricks pull request #10
Opened 2021-04-20 10:40 UTC by arnaud-blanc

2021-04-20 10:42 UTC, ced37 approved these changes, later dismissed

2021-04-20 15:07 UTC, floriane-cheneveau approved these changes

2021-04-20 15:08 UTC, floriane-cheneveau submitted a review, later dismissed

2021-04-21 07:15 UTC, RomainClair requested changes
Applying the SQL file on an existing DB result in errors : 
You can't drop a table refered by foreign keys.
You'll probably have to choose wisely the order of the drops

2021-04-21 08:57 UTC, ced37 approved these changes

2021-04-21 09:32 UTC, RomainClair approved these changes

2021-04-21 09:32 UTC, merged